export enum RentingStatus {
  WAITING = "WAITING",
  PREPARE = "PREPARE",
  SHIPPING = "SHIPPING",
  DELIVERED = "DELIVERED",
  RETURNED = "RETURNED",
  CHECKING = "CHECKING",
  VERIFIED = "VERIFIED",
}
